language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install pytest-cov
  - pip install codecov
  - python setup.py install
script:
  - pytest --cov=tests/ --cov-report term
after_success:
  - codecov
