language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install pytest-cov
  - python setup.py install
script:
  - pytest --cov=wdtools tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
