name: wdtools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas
  - lmfit
  - emcee
  - sphinx-autoapi
  - astropy
  - sphinx
  - scikit-learn
  - corner
  - tensorflow
  - jupyter
  - prompt_toolkit
  - ipython
  - keras