name: wdtools
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python==3.6
  - keras
  - emcee
  - lmfit
  - astropy
  - scikit-learn
  - sphinx
  - sphinx-autoapi
  - corner
  - sphinxcontrib-bibtex
  - nb_conda
  - pandas